### ISSUE TITLE
Need to specify VO explicitly for deployments

### ISSUE THREAD

**Issue by tdviet** [AI4EOSC/ai4-papi#11]
At the moment, the VO memberships are obtained from get_user_info https://github.com/AI4EOSC/ai4-papi/blob/master/ai4papi/auth.py#L87. However, if the user has memberships of more than one VO supported by the platform (most of us), it is not clear which VO the deployment belongs to. 

Therefore, VO should be explicitly given as a parameter, at least for creating deployment. The authentication process should check if the user has membership of the VO, otherwise it fails.

**Comment by IgnacioHeredia** [comment]
Hi @tdviet ,

the behaviour you are describing is already implemented:
* VO as a parameter [here](https://github.com/AI4EOSC/ai4-papi/blob/bec177f7f9481af7fb7a842d5d70cbc942d307ba/etc/userconf.yaml#L14-L18) and [here](https://github.com/AI4EOSC/ai4-papi/blob/bec177f7f9481af7fb7a842d5d70cbc942d307ba/ai4papi/routers/v1/info.py#L48-L50)
* check VO membership is not yet implemented because we are still not deploying to namespaces. But I can write the checks nevertheless to advance some of the work.

**Comment by tdviet** [comment]
Hi @IgnacioHeredia ,

thank you for quick answers (for both issues). I didn't aware that the VO is given in the configuration of the deployment.

In my personal opinion, the explicit VO as an extra parameter of all functions of the deployment module may help:
- for the create_deployment(), the deployment configuration is more generic, VO-independent. The CLI/dashboard don't have to modify the deployment configuration because of changing VO.
- for the get_deployments() function, without the VO as the parameter, we will have to list all namespaces.

**Comment by IgnacioHeredia** [comment]
Yes, that could make sense. I'll leave the issue open till this is implemented then.

**Comment by IgnacioHeredia** [comment]
Done in #16.
